title: DigiLiv.se – En resa genom dagens digitala livet
email: uruba@outlook.com
description: >
  Tips, råd, berättelser om datorer och teknik till alla människor!
url: "https://digiliv.se"
lang: "sv"
facebook_username: digiliv
twitter_username: digilivse
github_username:  jekyll
permalink: /:categories/:title
responsive_image:
  template: _includes/img.html
  sizes:
    - width: 1000
  output_path_format: assets/%{dirname}/%{width}/%{basename}
js_dest: /js
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
  permalinks:
    category: '/kategori/:name/'

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-feed
  - jekyll-responsive-image
  - liquid_reading_time
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
  - build_production.bat
