baseURL = "https://digiliv.se/"
languageCode = "sv-SE"
title = "allt nytt i våra digitala liv"
theme = "digiliv"
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = false
RemovePathAccents = true
preserveTaxonomyNames = true
#disableKinds = ["taxonomyTerm"]

#[permalinks]
#  page = ""

[taxonomies]
  category = "kategori"

[params]
  facebookUsername="digiliv"
  twitterUsername="digilivse"
  slogan="Allt nytt i våra digitala liv"
